apiVersion: apps/v1
kind: Deployment
metadata:
  name: story-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: story
  template:
    metadata:
      labels:
        app: story
    spec:
      containers:
      - name: story-container
        image: alejomartinez8/kub-data-demo:3
        env:
          - name: STORY_FOLDER
            valueFrom:
              configMapKeyRef:
                name: data-store-env
                key: folder
        # Specify the volume for container
        volumeMounts:
          - mountPath: /app/story # The path in the contianer
            name: story-volume # The name of volume
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
      # List of volumes that can be mounted by containers belonging to the pod.
      volumes:
        - name: story-volume
          # --> emptyDir Type
          # emptyDir: {}
          # --> hostPath Type
          # hostPath:
          #   path: /data
          #   type: DirectoryOrCreate
          # --> persistentVolumeClaim Typ
          persistentVolumeClaim:
            claimName: host-pvc