apiVersion: v1
kind: PersistentVolume
metadata:
  name: host-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem # Filesystem or Block
  storageClassName: standard # Permissions
  accessModes:
    - ReadWriteOnce # read-write volume by a single node
    # - ReadOnlyMany # read only volume by a multiple node
    # - ReadWriteMany # read-write volume by a multiple node
  hostPath:
    path: /data
    type: DirectoryOrCreate
